export const menuItemsData = [
    {
      id: 1,
      name: 'Salmon Nicoise Salad',
      info: 'Beautifully roasted salmon is served overtop an artisan salad blend.',
      price: 13,
      img: "/images/salmon-nicoise-salad.png",
    },
    {
      id: 2,
      name: 'Egg White Shakshuka',
      info: 'Topped with our house made shakshuka sauce, this dish is equal parts smoky.',
      price: 12,
      img: '/images/shakshuka.png',
    },
    {
      id: 3,
      name: 'Air Fried Falafel Bowl',
      info: 'This protein-packed dish is light yet hearty.',
      price: 10,
      img: '/images/falafel-boowl.png',
    },
    {
      id: 4,
      name: 'Kung Pao Chicken',
      info: 'Our healthy spin on this authentic Chinese dish brings the heat.',
      price: 15,
      img: '/images/kung-pao-chicken-plate-1.png',
    },
    {
      id: 5,
      name: 'Lemon Caper Grilled Salmon',
      info: 'Delicately grilled salmon is served over a bed of fresh spinach.',
      price: 13.5,
      img: '/images/lemon_caper_salmon.png',
    },
    {
      id: 6,
      name: 'Vegan Stuffed Portabella',
      info: 'This plant-based meal is satisfying, healthy, and packed with delicious flavors!',
      price: 11,
      img: '/images/mushroom-1.png',
    },
    {
      id: 7,
      name: 'Lemon Pepper Steak 2.0',
      info: 'We’ve upgraded our Lemon Pepper Steak & made it better than ever!',
      price: 15,
      img: '/images/lemon_pepper_steak.png',
    },
    {
      id: 8,
      name: 'Thai Basil Shrimp Curry',
      info: 'Our version of this popular Thai street food dish will have your tastebuds craving more!',
      price: 14,
      img: '/images/shrimp_thai_curry.png',
    },
    {
      id: 9,
      name: 'Butter Chicken',
      info: 'If your go-to Indian dish is butter chicken, then you will fall in love with our low calorie version!',
      price: 13,
      img: '/images/Butter-Chicken.png',
    },
    {
      id: 10,
      name: 'Roast Beef Wrap',
      info: 'Roasted top round beef is thinly sliced and wrapped in a whole wheat tortilla.',
      price: 12,
      img: '/images/10-28-2019_0000_Roast-Beef-Wrap-.png',
    },
    {
      id: 11,
      name: 'Pollo Asado',
      info: 'Our take on an authentic Spanish dish bursting with irresistible flavor!',
      price: 13,
      img: '/images/pollo_asado-1.png',
    },
    {
      id: 12,
      name: 'Stefano’s Polpette',
      info: 'No one does healthy Italian comfort food quite like Chef Stefano!',
      price: 10,
      img: '/images/web_layers_0009_Stefano’s-Polpette.png',
    },
    {
      id: 13,
      name: 'Low Carb Breakfast',
      info: 'Low in carb, but big in flavor!',
      price: 10,
      img: '/images/lowcarb_breakfast.png',
    },
    {
      id: 14,
      name: 'Tofu Sweet Chili Soba',
      info: 'Turn up the heat with tofu marinated in our sweet and tangy chili sauce!',
      price: 12,
      img: '/images/web_layers_0005_Tofu-Sweet-Chili-Soba.png',
    },
    {
      id: 15,
      name: 'Carnitas Breakfast Bowl',
      info: 'Start your day in the most flavorful way!',
      price: 12,
      img: '/images/new_products_0003_Carnitas-Breakfast-Bowl-.png',
    },
    {
      id: 16,
      name: 'Vegan Bolognese w/ Spaghetti Squash',
      info: 'Flavors so complex and hearty that you won’t even miss the meat! ',
      price: 13,
      img: '/images/0003_Vegan-Bolognase-and-Spaghetti.png',
    },
    {
      id: 17,
      name: 'Low Carb Bulgogi',
      info: 'Our low carb spin on Beef Bulgogi will have your taste buds craving more! ',
      price: 13,
      img: '/images/web_layers_0026_low-carb-bulgolgi-.png',
    },
  ];